CREATE TABLE `blog_drafts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`workspaceId` int,
	`voiceProfileId` int,
	`title` varchar(500) NOT NULL,
	`status` enum('brief','outline','draft','final','published') NOT NULL DEFAULT 'draft',
	`topic` text,
	`primaryKeyword` varchar(255),
	`secondaryKeywords` json,
	`searchIntent` varchar(100),
	`audience` varchar(255),
	`funnelStage` varchar(100),
	`geoTarget` varchar(255),
	`brandName` varchar(255),
	`ctaGoal` varchar(255),
	`internalNotes` text,
	`tone` varchar(100),
	`complexityLevel` varchar(100),
	`readingLevel` varchar(100),
	`pointOfView` varchar(50),
	`outputLanguage` varchar(50) DEFAULT 'en',
	`blogLength` varchar(50) DEFAULT 'medium',
	`customWordCount` int,
	`blogLayout` varchar(100) DEFAULT 'standard',
	`includeIntro` boolean DEFAULT true,
	`includeTldr` boolean DEFAULT false,
	`includeKeyTakeaways` boolean DEFAULT false,
	`includeFaq` boolean DEFAULT false,
	`includeConclusion` boolean DEFAULT true,
	`includeCtaSection` boolean DEFAULT true,
	`includeSchemaFaq` boolean DEFAULT false,
	`metaTitle` varchar(255),
	`metaDescription` text,
	`slugSuggestion` varchar(255),
	`headingDepth` varchar(20) DEFAULT 'h2-h3',
	`keywordDensityTarget` float DEFAULT 1.5,
	`useSemanticEntities` boolean DEFAULT true,
	`useNlpTerms` boolean DEFAULT true,
	`sliderFormality` int DEFAULT 50,
	`sliderOpinionated` int DEFAULT 50,
	`sliderElaborate` int DEFAULT 50,
	`sliderBold` int DEFAULT 50,
	`sliderStorytelling` int DEFAULT 50,
	`sliderHumor` int DEFAULT 50,
	`sliderPersuasion` int DEFAULT 50,
	`sliderTechnical` int DEFAULT 50,
	`contentBrief` text,
	`contentOutline` text,
	`contentDraft` text,
	`contentFinal` text,
	`wordCount` int DEFAULT 0,
	`isDemo` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_drafts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `export_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`blogDraftId` int,
	`exportFormat` varchar(50) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `export_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `generated_images` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`blogDraftId` int,
	`prompt` text NOT NULL,
	`revisedPrompt` text,
	`imageUrl` text,
	`altText` text,
	`style` varchar(100) DEFAULT 'photorealistic',
	`aspectRatio` varchar(20) DEFAULT '16:9',
	`isDemo` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `generated_images_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `repurpose_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`workspaceId` int,
	`voiceProfileId` int,
	`title` varchar(500),
	`sourceContent` text,
	`sourceFileName` varchar(255),
	`targetTopic` text,
	`targetFormat` varchar(100) DEFAULT 'blog',
	`transformationInstructions` text,
	`transformationPlan` text,
	`outputContent` text,
	`status` enum('pending','planning','generating','complete') NOT NULL DEFAULT 'pending',
	`messages` json,
	`isDemo` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `repurpose_sessions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`workspaceId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`category` varchar(100) DEFAULT 'general',
	`templateType` enum('prompt_preset','seo_config','voice_layout','industry','local_seo','thought_leadership','agency') NOT NULL DEFAULT 'prompt_preset',
	`config` json,
	`voiceProfileId` int,
	`blogLayout` varchar(100),
	`isPublic` boolean DEFAULT false,
	`isDemo` boolean NOT NULL DEFAULT false,
	`usageCount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `templates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `usage_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`action` varchar(100) NOT NULL,
	`resourceType` varchar(100),
	`resourceId` int,
	`metadata` json,
	`wordsGenerated` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `usage_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`defaultVoiceProfileId` int,
	`defaultCtaStyle` varchar(100) DEFAULT 'soft',
	`defaultBlogLength` varchar(50) DEFAULT 'medium',
	`defaultBlogLayout` varchar(100) DEFAULT 'standard',
	`defaultLanguage` varchar(10) DEFAULT 'en',
	`englishVariant` enum('american','british','australian','canadian') DEFAULT 'american',
	`defaultKeywordDensity` float DEFAULT 1.5,
	`defaultHeadingDepth` varchar(20) DEFAULT 'h2-h3',
	`restrictedWords` json,
	`brandPhrases` json,
	`competitorNames` json,
	`citationPreferences` varchar(100) DEFAULT 'inline',
	`imageStyle` varchar(100) DEFAULT 'photorealistic',
	`imageAspectRatio` varchar(20) DEFAULT '16:9',
	`onboardingCompleted` boolean DEFAULT false,
	`onboardingSteps` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_settings_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `voice_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`workspaceId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`voiceType` enum('personal','brand','team','campaign') NOT NULL DEFAULT 'personal',
	`tags` json,
	`dnaFormality` int DEFAULT 50,
	`dnaOpinionated` int DEFAULT 50,
	`dnaElaborate` int DEFAULT 50,
	`dnaBold` int DEFAULT 50,
	`dnaStorytelling` int DEFAULT 50,
	`dnaHumor` int DEFAULT 50,
	`dnaPersuasion` int DEFAULT 50,
	`dnaTechnical` int DEFAULT 50,
	`summaryDescription` text,
	`doRules` json,
	`dontRules` json,
	`signaturePhrases` json,
	`sentencePatternExamples` json,
	`preferredOpenings` json,
	`preferredTransitions` json,
	`preferredCtaStyles` json,
	`vocabularyPreferences` json,
	`forbiddenPhrases` json,
	`sampleExcerpts` json,
	`confidenceScore` float DEFAULT 0,
	`analysisData` json,
	`isDemo` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `voice_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `voice_source_files` (
	`id` int AUTO_INCREMENT NOT NULL,
	`voiceProfileId` int NOT NULL,
	`userId` int NOT NULL,
	`fileName` varchar(255),
	`fileType` varchar(50),
	`content` text NOT NULL,
	`wordCount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `voice_source_files_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `workspaces` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`isDefault` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `workspaces_id` PRIMARY KEY(`id`)
);
